apiVersion: batch/v1
kind: CronJob
metadata:
  name: jellyfin-backup
spec:
  schedule: "{{ .Values.backup.schedule }}"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: backup
            image: {{ .Values.backup.image.repository }}:{{ .Values.backup.image.tag }}
            command:
            - /bin/sh
            - -c
            - |
{{ .Values.backup.command | indent 14 }}
          restartPolicy: OnFailure
