kind: Deployment
apiVersion: apps/v1
metadata:
  name: calibre
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: calibre
  template:
    metadata:
      labels:
        app: calibre
    spec:
      {{- with .Values.deployment.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: calibre
        image: {{ .Values.deployment.image.repository }}:{{ .Values.deployment.image.tag }}
        ports:
        - name: web
          containerPort: 8083
        env:
        {{- range .Values.deployment.env }}
        - name: {{ .name }}
          value: {{ .value | quote }}
        {{- end }}
        volumeMounts:
        - name: config
          mountPath: /config
        - name: library
          mountPath: /calibre-library 
        - name: new-books
          mountPath: /cwa-book-ingest
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: calibre-config-pvc
      - name: library
        nfs:
          server: {{ .Values.nfs }}
          path: /volume1/data/media/books/library
      - name: new-books
        nfs:
          server: {{ .Values.nfs }}
          path: /volume1/data/media/books/new
