apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: calibre
spec:
  entryPoints:
  - websecure
  routes:
    - match: Host(`calibre.{{ .Values.domain }}`)
      kind: Rule
      services:
      - name: calibre
        port: {{ .Values.service.port }}
