apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: calibre-config
spec:
  storageClassName: {{ .Values.pvc.storageClassName }}
  accessModes:
    {{- range .Values.pvc.accessModes }}
    - {{ . }}
    {{- end }}
  resources:
    requests:
      storage: {{ .Values.pvc.size }}
