apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: calibre-config
  namespace: media
spec:
  storageClassName: local-path
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
