pvc:
  storageClassName: nfs-sc
  accessModes:
  - ReadWriteOnce
  size: 1Gi

deployment:
  nodeSelector:
    size: s
  image:
    repository: crocodilestick/calibre-web-automated
    tag: "V3.0.4"
  replicas: 1
  env:
  - name: PUID
    value: "1000"
  - name: PGID
    value: "1000"
  - name: CUSTOM_USER
    value: <path:secret/data/media/calibre#user>
  - name: PASSWORD
    value: <path:secret/data/media/calibre#password>

service:
  type: ClusterIP
  port: 8083

domain: <path:secret/data/infra#domain>
nfs: <path:secret/data/infra#nfs>
