apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-config
  namespace: media
spec:
  storageClassName: nfs-sc
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
