name: Validate Kubernetes Manifests

on:
  pull_request:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  validate-k8s-manifests:
    runs-on: ubuntu-latest
    steps:
    - name: Validate k8s manifests
      uses: home-kops/actions/.github/workflows/validate-k8s-manifests@main
